// backend/src/scripts/seed-questions.ts
import mongoose from 'mongoose';
import { config } from '../config/env.js';
import { Question } from '../models/Question.js';
import { logger } from '../utils/logger.js';

const questionsData = [
  // ============================================
  // CONTROLES ORGANIZACIONAIS (5.1 a 5.37)
  // ============================================

  // 5.1
  {
    controlId: '5.1',
    controlName: 'Políticas de segurança da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização possui políticas de segurança da informação formalmente documentadas e aprovadas pela direção?',
    objective: 'Verificar se as políticas de segurança da informação estão formalmente estabelecidas e aprovadas.',
    answerImplemented: 'Políticas documentadas, aprovadas pela direção, publicadas, comunicadas e revisadas anualmente.',
    answerPartial: 'Políticas documentadas, mas não estão totalmente aprovadas ou não foram comunicadas a todos.',
    answerNotImplemented: 'Não existem políticas de segurança da informação formalmente documentadas.',
    guidance: 'Documento de Políticas de Segurança da Informação, Ata de aprovação, Comunicados internos.',
    order: 1,
    active: true,
  },
  // 5.2
  {
    controlId: '5.2',
    controlName: 'Funções e responsabilidades de segurança da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'As funções e responsabilidades de segurança da informação estão claramente definidas e atribuídas?',
    objective: 'Verificar se as responsabilidades de segurança estão formalmente definidas.',
    answerImplemented: 'Funções e responsabilidades definidas em documento formal, com alocação clara.',
    answerPartial: 'Funções definidas, mas não formalmente documentadas ou com sobreposição.',
    answerNotImplemented: 'Não há definição formal de funções e responsabilidades.',
    guidance: 'Descrição de cargos, Matriz de responsabilidades, Política de funções.',
    order: 1,
    active: true,
  },
  // 5.3
  {
    controlId: '5.3',
    controlName: 'Segregação de funções',
    controlCategory: 'Controles Organizacionais',
    text: 'Existe segregação de funções para evitar conflitos de interesse?',
    objective: 'Verificar se funções conflitantes são segregadas.',
    answerImplemented: 'Funções conflitantes segregadas com matriz documentada.',
    answerPartial: 'Segregação parcial implementada.',
    answerNotImplemented: 'Não existe segregação de funções.',
    guidance: 'Matriz de segregação, Descrição de cargos.',
    order: 1,
    active: true,
  },
  // 5.4
  {
    controlId: '5.4',
    controlName: 'Responsabilidades da direção',
    controlCategory: 'Controles Organizacionais',
    text: 'A direção demonstra compromisso com a segurança da informação?',
    objective: 'Verificar o compromisso da alta direção.',
    answerImplemented: 'Direção comprometida com recursos e participação ativa.',
    answerPartial: 'Compromisso limitado.',
    answerNotImplemented: 'Sem compromisso da direção.',
    guidance: 'Atas de reuniões, Orçamento de segurança.',
    order: 1,
    active: true,
  },
  // 5.5
  {
    controlId: '5.5',
    controlName: 'Contato com autoridades',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização mantém contatos com autoridades regulatórias?',
    objective: 'Verificar canais de comunicação com autoridades.',
    answerImplemented: 'Contatos estabelecidos e mantidos.',
    answerPartial: 'Alguns contatos estabelecidos.',
    answerNotImplemented: 'Sem contatos com autoridades.',
    guidance: 'Lista de contatos, Registros de comunicação.',
    order: 1,
    active: true,
  },
  // 5.6
  {
    controlId: '5.6',
    controlName: 'Contato com grupos de interesses especial',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização participa de grupos de interesse em segurança?',
    objective: 'Verificar participação em fóruns e grupos.',
    answerImplemented: 'Participação ativa em grupos.',
    answerPartial: 'Participação limitada.',
    answerNotImplemented: 'Sem participação.',
    guidance: 'Registros de participação, Certificações.',
    order: 1,
    active: true,
  },
  // 5.7
  {
    controlId: '5.7',
    controlName: 'Inteligência de ameaças',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização coleta e analisa informações sobre ameaças?',
    objective: 'Verificar processo de inteligência de ameaças.',
    answerImplemented: 'Processo formal de inteligência implementado.',
    answerPartial: 'Coleta sem análise estruturada.',
    answerNotImplemented: 'Sem coleta de informações.',
    guidance: 'Relatórios de inteligência, Fontes de informação.',
    order: 1,
    active: true,
  },
  // 5.8
  {
    controlId: '5.8',
    controlName: 'Gestão de projetos de segurança da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'Os projetos de segurança são gerenciados com metodologia adequada?',
    objective: 'Verificar gestão de projetos de segurança.',
    answerImplemented: 'Metodologia formal implementada.',
    answerPartial: 'Gestão parcial.',
    answerNotImplemented: 'Sem gestão formal.',
    guidance: 'Planos de projeto, Relatórios.',
    order: 1,
    active: true,
  },
  // 5.9
  {
    controlId: '5.9',
    controlName: 'Inventário de ativos de informação',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização mantém inventário atualizado de ativos de informação?',
    objective: 'Verificar inventário de ativos.',
    answerImplemented: 'Inventário completo e atualizado.',
    answerPartial: 'Inventário incompleto ou desatualizado.',
    answerNotImplemented: 'Sem inventário.',
    guidance: 'Inventário de ativos, Política de gestão.',
    order: 1,
    active: true,
  },
  // 5.10
  {
    controlId: '5.10',
    controlName: 'Classificação da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'As informações são classificadas por sensibilidade?',
    objective: 'Verificar classificação de informações.',
    answerImplemented: 'Esquema de classificação implementado.',
    answerPartial: 'Esquema existe mas não é consistente.',
    answerNotImplemented: 'Sem classificação.',
    guidance: 'Política de classificação, Etiquetas.',
    order: 1,
    active: true,
  },
  // 5.11
  {
    controlId: '5.11',
    controlName: 'Etiquetagem de ativos',
    controlCategory: 'Controles Organizacionais',
    text: 'Os ativos de informação são etiquetados conforme sua classificação?',
    objective: 'Verificar etiquetagem de ativos.',
    answerImplemented: 'Etiquetagem implementada conforme classificação.',
    answerPartial: 'Etiquetagem parcial.',
    answerNotImplemented: 'Sem etiquetagem.',
    guidance: 'Política de etiquetagem, Exemplos de etiquetas.',
    order: 1,
    active: true,
  },
  // 5.12
  {
    controlId: '5.12',
    controlName: 'Gestão da capacidade',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização gerencia a capacidade de recursos de TI?',
    objective: 'Verificar gestão de capacidade.',
    answerImplemented: 'Gestão de capacidade implementada.',
    answerPartial: 'Gestão parcial.',
    answerNotImplemented: 'Sem gestão de capacidade.',
    guidance: 'Planos de capacidade, Monitoramento.',
    order: 1,
    active: true,
  },
  // 5.13
  {
    controlId: '5.13',
    controlName: 'Registro, inventário e controle de mídias',
    controlCategory: 'Controles Organizacionais',
    text: 'As mídias são registradas e controladas adequadamente?',
    objective: 'Verificar controle de mídias.',
    answerImplemented: 'Controle completo de mídias.',
    answerPartial: 'Controle parcial.',
    answerNotImplemented: 'Sem controle de mídias.',
    guidance: 'Inventário de mídias, Política de controle.',
    order: 1,
    active: true,
  },
  // 5.14
  {
    controlId: '5.14',
    controlName: 'Transferência de mídias',
    controlCategory: 'Controles Organizacionais',
    text: 'A transferência de mídias é controlada e registrada?',
    objective: 'Verificar controle de transferência.',
    answerImplemented: 'Transferência controlada e registrada.',
    answerPartial: 'Controle parcial.',
    answerNotImplemented: 'Sem controle de transferência.',
    guidance: 'Registros de transferência, Política.',
    order: 1,
    active: true,
  },
  // 5.15
  {
    controlId: '5.15',
    controlName: 'Descarte de mídia',
    controlCategory: 'Controles Organizacionais',
    text: 'O descarte de mídias é realizado de forma segura?',
    objective: 'Verificar descarte seguro de mídias.',
    answerImplemented: 'Descarte seguro implementado.',
    answerPartial: 'Descarte parcialmente seguro.',
    answerNotImplemented: 'Sem procedimento de descarte.',
    guidance: 'Procedimento de descarte, Certificados.',
    order: 1,
    active: true,
  },
  // 5.16
  {
    controlId: '5.16',
    controlName: 'Funções e responsabilidades para gestão de incidentes',
    controlCategory: 'Controles Organizacionais',
    text: 'As funções para gestão de incidentes estão definidas?',
    objective: 'Verificar definição de funções para incidentes.',
    answerImplemented: 'Funções definidas e comunicadas.',
    answerPartial: 'Funções definidas mas não comunicadas.',
    answerNotImplemented: 'Sem definição de funções.',
    guidance: 'Plano de resposta a incidentes, Matriz de funções.',
    order: 1,
    active: true,
  },
  // 5.17
  {
    controlId: '5.17',
    controlName: 'Procedimentos de resposta a incidentes',
    controlCategory: 'Controles Organizacionais',
    text: 'Existem procedimentos documentados para resposta a incidentes?',
    objective: 'Verificar procedimentos de resposta.',
    answerImplemented: 'Procedimentos documentados e testados.',
    answerPartial: 'Procedimentos existem mas não são testados.',
    answerNotImplemented: 'Sem procedimentos de resposta.',
    guidance: 'Plano de resposta, Relatórios de testes.',
    order: 1,
    active: true,
  },
  // 5.18
  {
    controlId: '5.18',
    controlName: 'Documentação de evidências',
    controlCategory: 'Controles Organizacionais',
    text: 'As evidências de incidentes são documentadas?',
    objective: 'Verificar documentação de evidências.',
    answerImplemented: 'Evidências documentadas e preservadas.',
    answerPartial: 'Documentação parcial.',
    answerNotImplemented: 'Sem documentação.',
    guidance: 'Registros de incidentes, Evidências.',
    order: 1,
    active: true,
  },
  // 5.19
  {
    controlId: '5.19',
    controlName: 'Avaliação de eventos de segurança da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'Os eventos de segurança são avaliados adequadamente?',
    objective: 'Verificar avaliação de eventos.',
    answerImplemented: 'Eventos avaliados e classificados.',
    answerPartial: 'Avaliação parcial.',
    answerNotImplemented: 'Sem avaliação.',
    guidance: 'Registros de eventos, Classificação.',
    order: 1,
    active: true,
  },
  // 5.20
  {
    controlId: '5.20',
    controlName: 'Resposta a incidentes',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização responde adequadamente a incidentes?',
    objective: 'Verificar resposta a incidentes.',
    answerImplemented: 'Resposta adequada e documentada.',
    answerPartial: 'Resposta parcial.',
    answerNotImplemented: 'Sem resposta formal.',
    guidance: 'Plano de resposta, Relatórios de incidentes.',
    order: 1,
    active: true,
  },
  // 5.21
  {
    controlId: '5.21',
    controlName: 'Aprendizado com incidentes',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização aprende com os incidentes ocorridos?',
    objective: 'Verificar aprendizado com incidentes.',
    answerImplemented: 'Lições aprendidas documentadas e aplicadas.',
    answerPartial: 'Aprendizado parcial.',
    answerNotImplemented: 'Sem aprendizado.',
    guidance: 'Lições aprendidas, Melhorias implementadas.',
    order: 1,
    active: true,
  },
  // 5.22
  {
    controlId: '5.22',
    controlName: 'Gestão de continuidade de negócios',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização possui plano de continuidade de negócios?',
    objective: 'Verificar plano de continuidade.',
    answerImplemented: 'Plano completo e testado.',
    answerPartial: 'Plano existe mas não é testado.',
    answerNotImplemented: 'Sem plano de continuidade.',
    guidance: 'Plano de continuidade, Relatórios de testes.',
    order: 1,
    active: true,
  },
  // 5.23
  {
    controlId: '5.23',
    controlName: 'Segurança da informação para provedores de serviço',
    controlCategory: 'Controles Organizacionais',
    text: 'Os provedores de serviço estão sujeitos a requisitos de segurança?',
    objective: 'Verificar requisitos para provedores.',
    answerImplemented: 'Requisitos definidos e monitorados.',
    answerPartial: 'Requisitos existem mas não são monitorados.',
    answerNotImplemented: 'Sem requisitos para provedores.',
    guidance: 'Contratos com provedores, Política de terceiros.',
    order: 1,
    active: true,
  },
  // 5.24
  {
    controlId: '5.24',
    controlName: 'Gestão de fornecedores',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização gerencia os fornecedores com critérios de segurança?',
    objective: 'Verificar gestão de fornecedores.',
    answerImplemented: 'Gestão completa com critérios de segurança.',
    answerPartial: 'Gestão parcial.',
    answerNotImplemented: 'Sem gestão de fornecedores.',
    guidance: 'Política de fornecedores, Avaliações.',
    order: 1,
    active: true,
  },
  // 5.25
  {
    controlId: '5.25',
    controlName: 'Requisitos de segurança em contratos com fornecedores',
    controlCategory: 'Controles Organizacionais',
    text: 'Os contratos com fornecedores incluem requisitos de segurança?',
    objective: 'Verificar requisitos em contratos.',
    answerImplemented: 'Requisitos incluídos e monitorados.',
    answerPartial: 'Requisitos incluídos mas não monitorados.',
    answerNotImplemented: 'Sem requisitos de segurança.',
    guidance: 'Contratos, Cláusulas de segurança.',
    order: 1,
    active: true,
  },
  // 5.26
  {
    controlId: '5.26',
    controlName: 'Monitoramento de fornecedores',
    controlCategory: 'Controles Organizacionais',
    text: 'Os fornecedores são monitorados quanto à conformidade de segurança?',
    objective: 'Verificar monitoramento de fornecedores.',
    answerImplemented: 'Monitoramento contínuo implementado.',
    answerPartial: 'Monitoramento periódico.',
    answerNotImplemented: 'Sem monitoramento.',
    guidance: 'Relatórios de auditoria, Avaliações.',
    order: 1,
    active: true,
  },
  // 5.27
  {
    controlId: '5.27',
    controlName: 'Gestão de mudanças',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização possui processo formal de gestão de mudanças?',
    objective: 'Verificar processo de mudanças.',
    answerImplemented: 'Processo formal implementado.',
    answerPartial: 'Processo existe mas não é formal.',
    answerNotImplemented: 'Sem processo de mudanças.',
    guidance: 'Política de mudanças, Registros de mudanças.',
    order: 1,
    active: true,
  },
  // 5.28
  {
    controlId: '5.28',
    controlName: 'Avaliação de impacto da segurança da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização realiza avaliação de impacto em segurança da informação?',
    objective: 'Verificar avaliação de impacto.',
    answerImplemented: 'Avaliações realizadas e documentadas.',
    answerPartial: 'Avaliações parciais.',
    answerNotImplemented: 'Sem avaliação de impacto.',
    guidance: 'Relatórios de impacto, Metodologia.',
    order: 1,
    active: true,
  },
  // 5.29
  {
    controlId: '5.29',
    controlName: 'Avaliação de riscos',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização realiza avaliação de riscos regularmente?',
    objective: 'Verificar processo de avaliação de riscos.',
    answerImplemented: 'Avaliação regular e documentada.',
    answerPartial: 'Avaliação irregular.',
    answerNotImplemented: 'Sem avaliação de riscos.',
    guidance: 'Metodologia de riscos, Relatórios.',
    order: 1,
    active: true,
  },
  // 5.30
  {
    controlId: '5.30',
    controlName: 'Tratamento de riscos',
    controlCategory: 'Controles Organizacionais',
    text: 'Os riscos identificados são tratados adequadamente?',
    objective: 'Verificar tratamento de riscos.',
    answerImplemented: 'Tratamento completo com plano de ação.',
    answerPartial: 'Tratamento parcial.',
    answerNotImplemented: 'Sem tratamento de riscos.',
    guidance: 'Plano de tratamento, Acompanhamento.',
    order: 1,
    active: true,
  },
  // 5.31
  {
    controlId: '5.31',
    controlName: 'Plano de auditoria interna',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização possui plano de auditoria interna de segurança?',
    objective: 'Verificar plano de auditoria.',
    answerImplemented: 'Plano anual implementado.',
    answerPartial: 'Plano existe mas não é seguido.',
    answerNotImplemented: 'Sem plano de auditoria.',
    guidance: 'Plano de auditoria, Relatórios.',
    order: 1,
    active: true,
  },
  // 5.32
  {
    controlId: '5.32',
    controlName: 'Conformidade com requisitos legais e regulatórios',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização está em conformidade com requisitos legais?',
    objective: 'Verificar conformidade legal.',
    answerImplemented: 'Total conformidade documentada.',
    answerPartial: 'Conformidade parcial.',
    answerNotImplemented: 'Sem conformidade.',
    guidance: 'Matriz de requisitos, Certificações.',
    order: 1,
    active: true,
  },
  // 5.33
  {
    controlId: '5.33',
    controlName: 'Análise crítica da segurança da informação',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização realiza análise crítica da segurança da informação?',
    objective: 'Verificar análise crítica.',
    answerImplemented: 'Análises realizadas e documentadas.',
    answerPartial: 'Análises irregulares.',
    answerNotImplemented: 'Sem análise crítica.',
    guidance: 'Relatórios de análise, Ações corretivas.',
    order: 1,
    active: true,
  },
  // 5.34
  {
    controlId: '5.34',
    controlName: 'Análise crítica da direção',
    controlCategory: 'Controles Organizacionais',
    text: 'A direção realiza análise crítica da segurança da informação?',
    objective: 'Verificar análise pela direção.',
    answerImplemented: 'Reuniões regulares com documentação.',
    answerPartial: 'Reuniões irregulares.',
    answerNotImplemented: 'Sem análise pela direção.',
    guidance: 'Atas de reuniões, Decisões.',
    order: 1,
    active: true,
  },
  // 5.35
  {
    controlId: '5.35',
    controlName: 'Comunicação com partes interessadas',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização comunica informações de segurança às partes interessadas?',
    objective: 'Verificar comunicação com partes interessadas.',
    answerImplemented: 'Comunicação formal e regular.',
    answerPartial: 'Comunicação irregular.',
    answerNotImplemented: 'Sem comunicação.',
    guidance: 'Política de comunicação, Registros.',
    order: 1,
    active: true,
  },
  // 5.36
  {
    controlId: '5.36',
    controlName: 'Gestão de documentos',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização possui sistema de gestão de documentos de segurança?',
    objective: 'Verificar gestão de documentos.',
    answerImplemented: 'Sistema completo implementado.',
    answerPartial: 'Sistema parcial.',
    answerNotImplemented: 'Sem gestão de documentos.',
    guidance: 'Política de documentos, Repositório.',
    order: 1,
    active: true,
  },
  // 5.37
  {
    controlId: '5.37',
    controlName: 'Registros e evidências',
    controlCategory: 'Controles Organizacionais',
    text: 'A organização mantém registros e evidências de conformidade?',
    objective: 'Verificar registros e evidências.',
    answerImplemented: 'Registros completos e organizados.',
    answerPartial: 'Registros parciais.',
    answerNotImplemented: 'Sem registros.',
    guidance: 'Política de registros, Evidências.',
    order: 1,
    active: true,
  },

  // ============================================
  // CONTROLES DE PESSOAS (6.1 a 6.8)
  // ============================================

  // 6.1
  {
    controlId: '6.1',
    controlName: 'Triagem e seleção de pessoas',
    controlCategory: 'Controles de Pessoas',
    text: 'A organização realiza triagem de segurança em candidatos a emprego?',
    objective: 'Verificar processo de triagem.',
    answerImplemented: 'Triagem completa em todos os candidatos.',
    answerPartial: 'Triagem parcial.',
    answerNotImplemented: 'Sem triagem de segurança.',
    guidance: 'Política de triagem, Registros de verificação.',
    order: 1,
    active: true,
  },
  // 6.2
  {
    controlId: '6.2',
    controlName: 'Termos e condições de trabalho',
    controlCategory: 'Controles de Pessoas',
    text: 'Os termos e condições de trabalho incluem obrigações de segurança?',
    objective: 'Verificar termos de trabalho.',
    answerImplemented: 'Termos completos com obrigações claras.',
    answerPartial: 'Termos parciais.',
    answerNotImplemented: 'Sem obrigações de segurança.',
    guidance: 'Contratos de trabalho, Política de segurança.',
    order: 1,
    active: true,
  },
  // 6.3
  {
    controlId: '6.3',
    controlName: 'Conscientização e treinamento',
    controlCategory: 'Controles de Pessoas',
    text: 'A organização oferece treinamento em segurança da informação?',
    objective: 'Verificar programa de treinamento.',
    answerImplemented: 'Programa regular e obrigatório.',
    answerPartial: 'Treinamento irregular.',
    answerNotImplemented: 'Sem treinamento.',
    guidance: 'Plano de treinamento, Registros de participação.',
    order: 1,
    active: true,
  },
  // 6.4
  {
    controlId: '6.4',
    controlName: 'Disciplina',
    controlCategory: 'Controles de Pessoas',
    text: 'A organização aplica medidas disciplinares para violações de segurança?',
    objective: 'Verificar processo disciplinar.',
    answerImplemented: 'Processo formal implementado.',
    answerPartial: 'Processo existente mas não aplicado.',
    answerNotImplemented: 'Sem processo disciplinar.',
    guidance: 'Política disciplinar, Registros de ocorrências.',
    order: 1,
    active: true,
  },
  // 6.5
  {
    controlId: '6.5',
    controlName: 'Responsabilidades pós-emprego',
    controlCategory: 'Controles de Pessoas',
    text: 'As responsabilidades de segurança continuam após o término do emprego?',
    objective: 'Verificar obrigações pós-emprego.',
    answerImplemented: 'Obrigações definidas e comunicadas.',
    answerPartial: 'Obrigações definidas mas não comunicadas.',
    answerNotImplemented: 'Sem obrigações pós-emprego.',
    guidance: 'Cláusulas contratuais, Termos de confidencialidade.',
    order: 1,
    active: true,
  },
  // 6.6
  {
    controlId: '6.6',
    controlName: 'Acordos de confidencialidade',
    controlCategory: 'Controles de Pessoas',
    text: 'Os colaboradores assinam acordos de confidencialidade?',
    objective: 'Verificar acordos de confidencialidade.',
    answerImplemented: 'Todos os colaboradores assinam.',
    answerPartial: 'Assinatura parcial.',
    answerNotImplemented: 'Sem acordos de confidencialidade.',
    guidance: 'Modelo de acordo, Registros de assinatura.',
    order: 1,
    active: true,
  },
  // 6.7
  {
    controlId: '6.7',
    controlName: 'Trabalho remoto',
    controlCategory: 'Controles de Pessoas',
    text: 'O trabalho remoto é realizado com segurança da informação?',
    objective: 'Verificar políticas de trabalho remoto.',
    answerImplemented: 'Políticas completas e aplicadas.',
    answerPartial: 'Políticas existentes mas não aplicadas.',
    answerNotImplemented: 'Sem políticas de trabalho remoto.',
    guidance: 'Política de trabalho remoto, Equipamentos seguros.',
    order: 1,
    active: true,
  },
  // 6.8
  {
    controlId: '6.8',
    controlName: 'Retorno ao trabalho presencial',
    controlCategory: 'Controles de Pessoas',
    text: 'O retorno ao trabalho presencial é seguro?',
    objective: 'Verificar segurança no retorno presencial.',
    answerImplemented: 'Procedimentos de segurança implementados.',
    answerPartial: 'Procedimentos parciais.',
    answerNotImplemented: 'Sem procedimentos.',
    guidance: 'Procedimento de retorno, Checklist.',
    order: 1,
    active: true,
  },

  // ============================================
  // CONTROLES FÍSICOS (7.1 a 7.14)
  // ============================================

  // 7.1
  {
    controlId: '7.1',
    controlName: 'Perímetro de segurança física',
    controlCategory: 'Controles Físicos',
    text: 'A organização possui perímetro de segurança física definido?',
    objective: 'Verificar perímetro de segurança.',
    answerImplemented: 'Perímetro definido e controlado.',
    answerPartial: 'Perímetro parcial.',
    answerNotImplemented: 'Sem perímetro de segurança.',
    guidance: 'Plantas de perímetro, Controles de acesso.',
    order: 1,
    active: true,
  },
  // 7.2
  {
    controlId: '7.2',
    controlName: 'Controles de acesso físico',
    controlCategory: 'Controles Físicos',
    text: 'Os acessos físicos são controlados adequadamente?',
    objective: 'Verificar controle de acesso físico.',
    answerImplemented: 'Controles completos com registro.',
    answerPartial: 'Controles parciais.',
    answerNotImplemented: 'Sem controle de acesso.',
    guidance: 'Política de acesso físico, Registros de acesso.',
    order: 1,
    active: true,
  },
  // 7.3
  {
    controlId: '7.3',
    controlName: 'Salas e escritórios seguros',
    controlCategory: 'Controles Físicos',
    text: 'As salas e escritórios são seguros?',
    objective: 'Verificar segurança de salas.',
    answerImplemented: 'Salas seguras com controles.',
    answerPartial: 'Segurança parcial.',
    answerNotImplemented: 'Salas não seguras.',
    guidance: 'Normas de segurança, Controles físicos.',
    order: 1,
    active: true,
  },
  // 7.4
  {
    controlId: '7.4',
    controlName: 'Segurança de salas de servidores',
    controlCategory: 'Controles Físicos',
    text: 'As salas de servidores são seguras fisicamente?',
    objective: 'Verificar segurança de servidores.',
    answerImplemented: 'Salas seguras com monitoramento.',
    answerPartial: 'Segurança parcial.',
    answerNotImplemented: 'Salas não seguras.',
    guidance: 'Controles de acesso, Climatização, Monitoramento.',
    order: 1,
    active: true,
  },
  // 7.5
  {
    controlId: '7.5',
    controlName: 'Proteção contra ameaças ambientais',
    controlCategory: 'Controles Físicos',
    text: 'A organização protege contra ameaças ambientais?',
    objective: 'Verificar proteção ambiental.',
    answerImplemented: 'Proteção completa implementada.',
    answerPartial: 'Proteção parcial.',
    answerNotImplemented: 'Sem proteção ambiental.',
    guidance: 'Sistemas de detecção, Prevenção de incêndio.',
    order: 1,
    active: true,
  },
  // 7.6
  {
    controlId: '7.6',
    controlName: 'Área de recepção',
    controlCategory: 'Controles Físicos',
    text: 'A área de recepção é segura?',
    objective: 'Verificar segurança da recepção.',
    answerImplemented: 'Recepção segura com controles.',
    answerPartial: 'Segurança parcial.',
    answerNotImplemented: 'Recepção não segura.',
    guidance: 'Controles de acesso, Registro de visitantes.',
    order: 1,
    active: true,
  },
  // 7.7
  {
    controlId: '7.7',
    controlName: 'Área de trabalho segura',
    controlCategory: 'Controles Físicos',
    text: 'As áreas de trabalho são seguras?',
    objective: 'Verificar segurança de áreas de trabalho.',
    answerImplemented: 'Áreas seguras com controles.',
    answerPartial: 'Segurança parcial.',
    answerNotImplemented: 'Áreas não seguras.',
    guidance: 'Política de área segura, Controles.',
    order: 1,
    active: true,
  },
  // 7.8
  {
    controlId: '7.8',
    controlName: 'Limpeza de mesa',
    controlCategory: 'Controles Físicos',
    text: 'A política de limpeza de mesa é aplicada?',
    objective: 'Verificar limpeza de mesa.',
    answerImplemented: 'Política aplicada e monitorada.',
    answerPartial: 'Política existe mas não é monitorada.',
    answerNotImplemented: 'Sem política de limpeza.',
    guidance: 'Política de limpeza, Auditorias.',
    order: 1,
    active: true,
  },
  // 7.9
  {
    controlId: '7.9',
    controlName: 'Limpeza de tela',
    controlCategory: 'Controles Físicos',
    text: 'A política de limpeza de tela é aplicada?',
    objective: 'Verificar limpeza de tela.',
    answerImplemented: 'Política aplicada e monitorada.',
    answerPartial: 'Política existe mas não é monitorada.',
    answerNotImplemented: 'Sem política de limpeza.',
    guidance: 'Política de limpeza, Bloqueio de tela.',
    order: 1,
    active: true,
  },
  // 7.10
  {
    controlId: '7.10',
    controlName: 'Descarte e reutilização segura de equipamentos',
    controlCategory: 'Controles Físicos',
    text: 'O descarte de equipamentos é realizado com segurança?',
    objective: 'Verificar descarte seguro.',
    answerImplemented: 'Descarte seguro com certificação.',
    answerPartial: 'Descarte parcial.',
    answerNotImplemented: 'Sem procedimento de descarte.',
    guidance: 'Procedimento de descarte, Certificados.',
    order: 1,
    active: true,
  },
  // 7.11
  {
    controlId: '7.11',
    controlName: 'Equipamentos de terceiros',
    controlCategory: 'Controles Físicos',
    text: 'Os equipamentos de terceiros são controlados?',
    objective: 'Verificar controle de equipamentos de terceiros.',
    answerImplemented: 'Controles completos implementados.',
    answerPartial: 'Controles parciais.',
    answerNotImplemented: 'Sem controles.',
    guidance: 'Política de terceiros, Registros.',
    order: 1,
    active: true,
  },
  // 7.12
  {
    controlId: '7.12',
    controlName: 'Propriedade de ativos',
    controlCategory: 'Controles Físicos',
    text: 'A propriedade dos ativos é registrada e controlada?',
    objective: 'Verificar propriedade de ativos.',
    answerImplemented: 'Registros completos de propriedade.',
    answerPartial: 'Registros parciais.',
    answerNotImplemented: 'Sem registros de propriedade.',
    guidance: 'Inventário de ativos, Registros.',
    order: 1,
    active: true,
  },
  // 7.13
  {
    controlId: '7.13',
    controlName: 'Monitoramento de áreas físicas',
    controlCategory: 'Controles Físicos',
    text: 'As áreas físicas são monitoradas adequadamente?',
    objective: 'Verificar monitoramento físico.',
    answerImplemented: 'Monitoramento completo com câmeras.',
    answerPartial: 'Monitoramento parcial.',
    answerNotImplemented: 'Sem monitoramento.',
    guidance: 'Sistema de CFTV, Registros de monitoramento.',
    order: 1,
    active: true,
  },
  // 7.14
  {
    controlId: '7.14',
    controlName: 'Proteção contra interrupções de energia',
    controlCategory: 'Controles Físicos',
    text: 'A organização protege contra interrupções de energia?',
    objective: 'Verificar proteção de energia.',
    answerImplemented: 'Proteção completa com nobreak e gerador.',
    answerPartial: 'Proteção parcial.',
    answerNotImplemented: 'Sem proteção de energia.',
    guidance: 'Nobreak, Gerador, Plano de contingência.',
    order: 1,
    active: true,
  },

  // ============================================
  // CONTROLES TECNOLÓGICOS (8.1 a 8.34)
  // ============================================

  // 8.1
  {
    controlId: '8.1',
    controlName: 'Política de segurança de rede',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui política de segurança de rede?',
    objective: 'Verificar política de segurança de rede.',
    answerImplemented: 'Política completa e aplicada.',
    answerPartial: 'Política existente mas não aplicada.',
    answerNotImplemented: 'Sem política de segurança de rede.',
    guidance: 'Política de rede, Diagramas de rede.',
    order: 1,
    active: true,
  },
  // 8.2
  {
    controlId: '8.2',
    controlName: 'Controles de acesso à rede',
    controlCategory: 'Controles Tecnológicos',
    text: 'Os acessos à rede são controlados adequadamente?',
    objective: 'Verificar controle de acesso à rede.',
    answerImplemented: 'Controles completos implementados.',
    answerPartial: 'Controles parciais.',
    answerNotImplemented: 'Sem controle de acesso.',
    guidance: 'Política de acesso, Firewall, NAC.',
    order: 1,
    active: true,
  },
  // 8.3
  {
    controlId: '8.3',
    controlName: 'Segmentação de rede',
    controlCategory: 'Controles Tecnológicos',
    text: 'A rede é segmentada adequadamente?',
    objective: 'Verificar segmentação de rede.',
    answerImplemented: 'Segmentação completa com VLANs.',
    answerPartial: 'Segmentação parcial.',
    answerNotImplemented: 'Sem segmentação.',
    guidance: 'Diagrama de rede, VLANs, Firewall.',
    order: 1,
    active: true,
  },
  // 8.4
  {
    controlId: '8.4',
    controlName: 'Controle de acesso a sistemas',
    controlCategory: 'Controles Tecnológicos',
    text: 'O acesso a sistemas é controlado adequadamente?',
    objective: 'Verificar controle de acesso a sistemas.',
    answerImplemented: 'Controles completos com RBAC.',
    answerPartial: 'Controles parciais.',
    answerNotImplemented: 'Sem controle de acesso.',
    guidance: 'Política de acesso, RBAC, Registros.',
    order: 1,
    active: true,
  },
  // 8.5
  {
    controlId: '8.5',
    controlName: 'Registro e monitoramento de acesso',
    controlCategory: 'Controles Tecnológicos',
    text: 'Os acessos são registrados e monitorados?',
    objective: 'Verificar registro de acessos.',
    answerImplemented: 'Registros completos e monitoramento.',
    answerPartial: 'Registros existentes mas não monitorados.',
    answerNotImplemented: 'Sem registros de acesso.',
    guidance: 'Logs de acesso, SIEM, Alertas.',
    order: 1,
    active: true,
  },
  // 8.6
  {
    controlId: '8.6',
    controlName: 'Gerenciamento de identidades',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui gestão de identidades?',
    objective: 'Verificar gestão de identidades.',
    answerImplemented: 'IAM completo implementado.',
    answerPartial: 'IAM parcial.',
    answerNotImplemented: 'Sem gestão de identidades.',
    guidance: 'IAM, Ciclo de vida de identidades.',
    order: 1,
    active: true,
  },
  // 8.7
  {
    controlId: '8.7',
    controlName: 'Gerenciamento de senhas',
    controlCategory: 'Controles Tecnológicos',
    text: 'As senhas são gerenciadas com políticas adequadas?',
    objective: 'Verificar política de senhas.',
    answerImplemented: 'Política completa com MFA.',
    answerPartial: 'Política existente mas sem MFA.',
    answerNotImplemented: 'Sem política de senhas.',
    guidance: 'Política de senhas, MFA, Gerenciador de senhas.',
    order: 1,
    active: true,
  },
  // 8.8
  {
    controlId: '8.8',
    controlName: 'Autenticação multifator',
    controlCategory: 'Controles Tecnológicos',
    text: 'A autenticação multifator é utilizada?',
    objective: 'Verificar uso de MFA.',
    answerImplemented: 'MFA implementado em todos os acessos.',
    answerPartial: 'MFA em alguns acessos.',
    answerNotImplemented: 'Sem MFA.',
    guidance: 'MFA, Política de autenticação.',
    order: 1,
    active: true,
  },
  // 8.9
  {
    controlId: '8.9',
    controlName: 'Controle de acesso a aplicações',
    controlCategory: 'Controles Tecnológicos',
    text: 'O acesso a aplicações é controlado?',
    objective: 'Verificar controle de acesso a aplicações.',
    answerImplemented: 'Controles completos implementados.',
    answerPartial: 'Controles parciais.',
    answerNotImplemented: 'Sem controle.',
    guidance: 'Política de acesso, RBAC.',
    order: 1,
    active: true,
  },
  // 8.10
  {
    controlId: '8.10',
    controlName: 'Controle de acesso a dados',
    controlCategory: 'Controles Tecnológicos',
    text: 'O acesso a dados é controlado adequadamente?',
    objective: 'Verificar controle de acesso a dados.',
    answerImplemented: 'Controles completos com DLP.',
    answerPartial: 'Controles parciais.',
    answerNotImplemented: 'Sem controle de acesso.',
    guidance: 'Política de acesso, DLP, Criptografia.',
    order: 1,
    active: true,
  },
  // 8.11
  {
    controlId: '8.11',
    controlName: 'Backup e recuperação',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização realiza backups e possui plano de recuperação?',
    objective: 'Verificar backup e recuperação.',
    answerImplemented: 'Backups regulares e testados.',
    answerPartial: 'Backups existentes mas não testados.',
    answerNotImplemented: 'Sem backups.',
    guidance: 'Política de backup, Testes de restauração.',
    order: 1,
    active: true,
  },
  // 8.12
  {
    controlId: '8.12',
    controlName: 'Criptografia de dados',
    controlCategory: 'Controles Tecnológicos',
    text: 'Os dados são criptografados adequadamente?',
    objective: 'Verificar criptografia de dados.',
    answerImplemented: 'Criptografia em repouso e trânsito.',
    answerPartial: 'Criptografia parcial.',
    answerNotImplemented: 'Sem criptografia.',
    guidance: 'Política de criptografia, TLS, AES.',
    order: 1,
    active: true,
  },
  // 8.13
  {
    controlId: '8.13',
    controlName: 'Proteção contra malware',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui proteção contra malware?',
    objective: 'Verificar proteção contra malware.',
    answerImplemented: 'Proteção completa com EDR.',
    answerPartial: 'Proteção básica.',
    answerNotImplemented: 'Sem proteção.',
    guidance: 'Antivírus, EDR, Política de updates.',
    order: 1,
    active: true,
  },
  // 8.14
  {
    controlId: '8.14',
    controlName: 'Proteção contra ransomware',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui proteção contra ransomware?',
    objective: 'Verificar proteção contra ransomware.',
    answerImplemented: 'Proteção completa com backup imutável.',
    answerPartial: 'Proteção básica.',
    answerNotImplemented: 'Sem proteção.',
    guidance: 'Backup imutável, EDR, Treinamento.',
    order: 1,
    active: true,
  },
  // 8.15
  {
    controlId: '8.15',
    controlName: 'Gestão de vulnerabilidades',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui gestão de vulnerabilidades?',
    objective: 'Verificar gestão de vulnerabilidades.',
    answerImplemented: 'Programa completo com scans.',
    answerPartial: 'Scans existentes mas sem remediação.',
    answerNotImplemented: 'Sem gestão.',
    guidance: 'Scanner de vulnerabilidades, Política de remediação.',
    order: 1,
    active: true,
  },
  // 8.16
  {
    controlId: '8.16',
    controlName: 'Monitoramento de segurança',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização monitora a segurança continuamente?',
    objective: 'Verificar monitoramento de segurança.',
    answerImplemented: 'Monitoramento 24x7 com SOC.',
    answerPartial: 'Monitoramento parcial.',
    answerNotImplemented: 'Sem monitoramento.',
    guidance: 'SIEM, SOC, Alertas.',
    order: 1,
    active: true,
  },
  // 8.17
  {
    controlId: '8.17',
    controlName: 'Análise de logs',
    controlCategory: 'Controles Tecnológicos',
    text: 'Os logs são analisados regularmente?',
    objective: 'Verificar análise de logs.',
    answerImplemented: 'Análise regular com SIEM.',
    answerPartial: 'Análise ocasional.',
    answerNotImplemented: 'Sem análise de logs.',
    guidance: 'SIEM, Política de retenção, Alertas.',
    order: 1,
    active: true,
  },
  // 8.18
  {
    controlId: '8.18',
    controlName: 'Proteção contra ataques de negação de serviço',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui proteção contra DDoS?',
    objective: 'Verificar proteção contra DDoS.',
    answerImplemented: 'Proteção completa com WAF/CDN.',
    answerPartial: 'Proteção básica.',
    answerNotImplemented: 'Sem proteção.',
    guidance: 'WAF, CDN, Plano de resposta.',
    order: 1,
    active: true,
  },
  // 8.19
  {
    controlId: '8.19',
    controlName: 'Gestão de patches',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui gestão de patches?',
    objective: 'Verificar gestão de patches.',
    answerImplemented: 'Programa completo com automação.',
    answerPartial: 'Patches aplicados manualmente.',
    answerNotImplemented: 'Sem gestão de patches.',
    guidance: 'Política de patches, Ferramenta de automação.',
    order: 1,
    active: true,
  },
  // 8.20
  {
    controlId: '8.20',
    controlName: 'Testes de intrusão',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização realiza testes de intrusão?',
    objective: 'Verificar testes de intrusão.',
    answerImplemented: 'Testes regulares com pentest.',
    answerPartial: 'Testes ocasionais.',
    answerNotImplemented: 'Sem testes.',
    guidance: 'Pentest, Relatórios, Remediação.',
    order: 1,
    active: true,
  },
  // 8.21
  {
    controlId: '8.21',
    controlName: 'Gerenciamento de dispositivos móveis',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui gerenciamento de dispositivos móveis?',
    objective: 'Verificar gestão de dispositivos móveis.',
    answerImplemented: 'MDM completo implementado.',
    answerPartial: 'MDM básico.',
    answerNotImplemented: 'Sem MDM.',
    guidance: 'MDM, Política de dispositivos.',
    order: 1,
    active: true,
  },
  // 8.22
  {
    controlId: '8.22',
    controlName: 'Política de segurança para dispositivos',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui política de segurança para dispositivos?',
    objective: 'Verificar política de dispositivos.',
    answerImplemented: 'Política completa e aplicada.',
    answerPartial: 'Política existente mas não aplicada.',
    answerNotImplemented: 'Sem política.',
    guidance: 'Política de dispositivos, BYOD.',
    order: 1,
    active: true,
  },
  // 8.23
  {
    controlId: '8.23',
    controlName: 'Gestão de ativos de TI',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui gestão de ativos de TI?',
    objective: 'Verificar gestão de ativos de TI.',
    answerImplemented: 'Gestão completa com inventário.',
    answerPartial: 'Gestão parcial.',
    answerNotImplemented: 'Sem gestão.',
    guidance: 'Inventário, Política de ativos.',
    order: 1,
    active: true,
  },
  // 8.24
  {
    controlId: '8.24',
    controlName: 'Gerenciamento de mudanças em TI',
    controlCategory: 'Controles Tecnológicos',
    text: 'As mudanças em TI são gerenciadas formalmente?',
    objective: 'Verificar gestão de mudanças em TI.',
    answerImplemented: 'Processo formal implementado.',
    answerPartial: 'Processo existente mas não formal.',
    answerNotImplemented: 'Sem gestão de mudanças.',
    guidance: 'Política de mudanças, ITIL.',
    order: 1,
    active: true,
  },
  // 8.25
  {
    controlId: '8.25',
    controlName: 'Gerenciamento de projetos de TI',
    controlCategory: 'Controles Tecnológicos',
    text: 'Os projetos de TI são gerenciados adequadamente?',
    objective: 'Verificar gestão de projetos de TI.',
    answerImplemented: 'Gestão formal implementada.',
    answerPartial: 'Gestão parcial.',
    answerNotImplemented: 'Sem gestão.',
    guidance: 'Metodologia de projetos, PMO.',
    order: 1,
    active: true,
  },
  // 8.26
  {
    controlId: '8.26',
    controlName: 'Conformidade com padrões técnicos',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização está em conformidade com padrões técnicos?',
    objective: 'Verificar conformidade técnica.',
    answerImplemented: 'Total conformidade documentada.',
    answerPartial: 'Conformidade parcial.',
    answerNotImplemented: 'Sem conformidade.',
    guidance: 'Padrões técnicos, Auditorias.',
    order: 1,
    active: true,
  },
  // 8.27
  {
    controlId: '8.27',
    controlName: 'Segurança de aplicações web',
    controlCategory: 'Controles Tecnológicos',
    text: 'As aplicações web são seguras?',
    objective: 'Verificar segurança de aplicações web.',
    answerImplemented: 'Segurança completa com WAF e SAST.',
    answerPartial: 'Segurança básica.',
    answerNotImplemented: 'Sem segurança.',
    guidance: 'WAF, SAST, DAST, OWASP.',
    order: 1,
    active: true,
  },
  // 8.28
  {
    controlId: '8.28',
    controlName: 'Segurança de APIs',
    controlCategory: 'Controles Tecnológicos',
    text: 'As APIs são seguras?',
    objective: 'Verificar segurança de APIs.',
    answerImplemented: 'Segurança completa com autenticação.',
    answerPartial: 'Segurança básica.',
    answerNotImplemented: 'Sem segurança.',
    guidance: 'Autenticação, Rate limiting, Validação.',
    order: 1,
    active: true,
  },
  // 8.29
  {
    controlId: '8.29',
    controlName: 'Segurança em nuvem',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui segurança em nuvem adequada?',
    objective: 'Verificar segurança em nuvem.',
    answerImplemented: 'Segurança completa com CSPM.',
    answerPartial: 'Segurança básica.',
    answerNotImplemented: 'Sem segurança.',
    guidance: 'CSPM, Política de nuvem, IAM.',
    order: 1,
    active: true,
  },
  // 8.30
  {
    controlId: '8.30',
    controlName: 'Segurança de containers',
    controlCategory: 'Controles Tecnológicos',
    text: 'Os containers são seguros?',
    objective: 'Verificar segurança de containers.',
    answerImplemented: 'Segurança completa implementada.',
    answerPartial: 'Segurança básica.',
    answerNotImplemented: 'Sem segurança.',
    guidance: 'Scan de vulnerabilidades, Política de containers.',
    order: 1,
    active: true,
  },
  // 8.31
  {
    controlId: '8.31',
    controlName: 'Análise de código fonte',
    controlCategory: 'Controles Tecnológicos',
    text: 'O código fonte é analisado quanto a vulnerabilidades?',
    objective: 'Verificar análise de código.',
    answerImplemented: 'Análise automática em CI/CD.',
    answerPartial: 'Análise manual.',
    answerNotImplemented: 'Sem análise.',
    guidance: 'SAST, CI/CD, Revisão de código.',
    order: 1,
    active: true,
  },
  // 8.32
  {
    controlId: '8.32',
    controlName: 'Testes de segurança em desenvolvimento',
    controlCategory: 'Controles Tecnológicos',
    text: 'A segurança é considerada no desenvolvimento?',
    objective: 'Verificar DevSecOps.',
    answerImplemented: 'DevSecOps implementado.',
    answerPartial: 'Segurança considerada mas não integrada.',
    answerNotImplemented: 'Sem segurança no desenvolvimento.',
    guidance: 'DevSecOps, Testes de segurança, CI/CD.',
    order: 1,
    active: true,
  },
  // 8.33
  {
    controlId: '8.33',
    controlName: 'Resposta a incidentes em TI',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui resposta a incidentes em TI?',
    objective: 'Verificar resposta a incidentes.',
    answerImplemented: 'Plano completo e testado.',
    answerPartial: 'Plano existe mas não é testado.',
    answerNotImplemented: 'Sem plano.',
    guidance: 'Plano de resposta, Runbooks.',
    order: 1,
    active: true,
  },
  // 8.34
  {
    controlId: '8.34',
    controlName: 'Recuperação de desastres em TI',
    controlCategory: 'Controles Tecnológicos',
    text: 'A organização possui plano de recuperação de desastres em TI?',
    objective: 'Verificar plano de recuperação.',
    answerImplemented: 'Plano completo e testado.',
    answerPartial: 'Plano existe mas não é testado.',
    answerNotImplemented: 'Sem plano.',
    guidance: 'Plano de recuperação, Testes de DR.',
    order: 1,
    active: true,
  },
];// ============================================
// FUNÇÃO PARA POPULAR O BANCO
// ============================================
async function seedQuestions() {
  try {
    await mongoose.connect(config.MONGODB_URI, {
      dbName: config.MONGODB_DB_NAME,
    });

    logger.info('📦 Conectado ao MongoDB');

    // Remover perguntas existentes
    const deletedCount = await Question.deleteMany({});
    logger.info(`🗑️ ${deletedCount.deletedCount} perguntas removidas`);

    // Inserir novas perguntas
    const result = await Question.insertMany(questionsData);
    logger.info(`✅ ${result.length} perguntas inseridas com sucesso`);

    // Exibir resumo por controle
    const grouped = result.reduce((acc, q) => {
      const key = q.controlId;
      if (!acc[key]) acc[key] = [];
      acc[key].push(q);
      return acc;
    }, {} as Record<string, any[]>);

    logger.info('📋 Resumo por controle:');
    Object.keys(grouped).forEach((key) => {
      const count = grouped[key]?.length || 0;
      logger.info(`  - ${key}: ${count} pergunta(s)`);
    });

    logger.info('✅ Seed de perguntas concluído com sucesso!');
    process.exit(0);
  } catch (error) {
    logger.error('❌ Erro ao popular perguntas:', error);
    process.exit(1);
  }
}

seedQuestions();