services:
  - type: web
    name: code-assessment-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Code_Assessment:28108610@cluster0.fznrq7c.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: code_assessment_super_secret_jwt_key_2026_change_in_production
      - key: JWT_REFRESH_SECRET
        value: code_assessment_super_secret_refresh_key_2026_change_in_production
      - key: PORT
        value: 3000

  - type: static
    name: code-assessment-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://code-assessment-backend.onrender.com